services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm i && npm run dev"
    environment:
      DATABASE_URL: 'postgresql://todo-user:todo-password@db:5432/todo-db'
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: todo-password
      POSTGRES_DB: todo-db
    ports:
      - '5433:5432' # Changed to 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
